// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fpop
List fpop(std::vector<double> vectData, double penalty, std::string change);
RcppExport SEXP _fpop_fpop(SEXP vectDataSEXP, SEXP penaltySEXP, SEXP changeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type vectData(vectDataSEXP);
    Rcpp::traits::input_parameter< double >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< std::string >::type change(changeSEXP);
    rcpp_result_gen = Rcpp::wrap(fpop(vectData, penalty, change));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fpop_fpop", (DL_FUNC) &_fpop_fpop, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_fpop(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
