# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' fpop with many cost functions
#' @description A fast implementation of the fpop algorithm with many cost functions available
#' @param vectData vector of data to segment
#' @param penalty the penalty coefficient. A positive number
#' @param change A string defining the kind of cost function to use
#' @return a list of two vectors and a value  = (changepoints, segment parameters, global cost).
#' 'changepoints' is the vector of changepoints (we give the last element of each segment).
#' 'parameters' is the vector of successive parameters of each segment
#' 'globalCost' is a number equal to the global cost of the graph-constrained segmentation
fpop <- function(vectData, penalty, change = "mean") {
    .Call(`_fpop_fpop`, vectData, penalty, change)
}

